version: 2

sources:
  - name: staging_dexscreener
    description: "Dexscreener data for token information"
    database: default
    schema: '4304875491083592'
    tables:
      - name: staging_coinbase
        description: "Dexscreener ticker data"
  - name: staging_coinbase
    description: "Coinbase data for token information"
    database: default
    schema: '4304875491083592'
    tables:
      - name: staging_coinbase
        description: "Coinbase ticker data"
  - name: staging_pumpfun_king_of_the_hill
    description: "Pump.fun data for token information"
    database: default
    schema: '4304875491083592'
    tables:
      - name: staging_pumpfun_king_of_the_hill
        description: "Pump.fun ticker data"
